export const titles = [
  'Drink a glass of water after waking up',
  'Read for 10 minutes every morning',
  'Meditate for five minutes daily',
  'Walk 8,000 steps each day',
  'Write three things you’re grateful for',
  'Stretch for five minutes after waking',
  'Go to bed before 11 p.m.',
  'Avoid phone use 30 minutes before sleep',
  'Plan tomorrow’s tasks every evening',
  'Eat at least one fruit daily',
  'Review personal goals every Sunday',
  'Do 20 push-ups every morning',
  'Spend 10 minutes learning something new',
  'Keep a daily expense log',
  'Practice deep breathing twice a day',
  'Compliment someone genuinely once a day',
  'Limit caffeine to one cup per day',
  'Journal thoughts before going to sleep',
  'Clean workspace before finishing work',
  'Spend 15 minutes outside daily'
];